### PR TITLE
Configure github actions to create draft releases when pushing tags

### PR DESCRIPTION
**Pull request by soliddanii**
Hello, as requested, i've been looking into getting the github actions working. Let's hope this fixes the workflow.

I've actually never used github actions before but after [some](https://sevic.dev/notes/electron-forge-publish-github/) [research](https://dev.to/erikhofer/build-and-publish-a-multi-platform-electron-app-on-github-3lnd) and a fair share of trial and error, I was able to get releases [on my fork](https://github.com/soliddanii/Mods-Manager-for-3Dmigoto/releases/tag/v1.8.4).

Some notes about the configuration:
- I changed ACCESS_TOKEN with GITHUB_TOKEN because thats what i saw in the documentation. The github token is a token automatically generated by github for each action with the appropiate permissions. Here is the [relevant documentation](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
- This configuration builds the application and generates a DRAFT release when a new tag is pushed, insteaf of on every push. You can trigger the action manually too. More on that later.
- Both windows and linux builds get generated. The zip file is the same as the manual release you were currently doing. I did test the windows zip release and encountered no issues. Did not test the .deb or .rpm packages due to a lack of time. I also want to research into packaging as AppImage as that is my prefered linux format.
- Upgraded the node version to the latest LTS, but feel free to change it if another version is needed for some reason.

Now, this is the easiest way I found to make new releases:
- After commiting the changes for a new version, run `npm version major|minor|patch` to automatically change the package.json version, and generate the tag. Here is the [npm version documentation.](https://docs.npmjs.com/cli/v6/commands/npm-version). For example, if package version is 1.8.1, and you run `npm version patch`, It will change to 1.8.2. If you run `npm version minor`, it will change to 1.9.0
- Then, push both the version change and the tag with: `git push --follow-tags`. Of course you can also generate the tags manually.
- Wait a few minutes to let the actions finish, then you will see the draft release with the artifacts. Just click on the edit button of the draft release to setup the description and discard/add any artifacts.

Let me know if you encounter any issues or want to suggest any change 👍

### CODE REVIEW

**Comment by XiaoLinXiaoZhu** [comment]
Thank you very much! It ran very successfully.🥰

 As for me, I'm still trying to figure out how to quickly get the process and the window and send it F10 to make ZZZ refresh itself, but I'm still at a loss.

I've tried with notepad.exe and I've been able to get the window and make it trigger the specified keystrokes, but I'm not able to reproduce this action with ZZZ, I can only get the ZZZ window and make it top.

In the new version :
- Optimised use IntersectionObserver instead of getBoundingClientRect() to reduce the number of page redraws. 
- Added a filter to view selected mods.
- Added an auto-apply option to make the app easier to use.
- Layout tweaks.

It seems that this mod manager is close to being the best it can be, with more likes and downloads and views on gameBanana than the venerable mod manager jasm. I've gone through the process of getting this mod manager from its humble beginnings to almost perfect, with thanks to your help along the way!🤗

I plan on dropping the ability to have ZZZ be able to auto-refresh after application, it's been a waste of my time and I don't have a clue at this point, it just seems too in-depth for me.😭

In the next version, I'm going to add the ability to add a cover to a mod by dragging and dropping an image, for which I have some learning to do.🧐

**Comment by XiaoLinXiaoZhu** [comment]
> ## Withhold Notice
> This Tool is withheld! It will be restricted until its rule violations are addressed.
> Type
> Softhold
> ### Withholder
> [BananaBot](https://gamebanana.com/members/1)
> ### Withhold Date
> 22h
> ### Rule Violations
> R.36: Manual Review Required
> Some submissions require a manual review by moderators.
> 
> ### Fix Instructions
> Please wait until a moderator has reviewed the submission

errr,after i publish the v1.8.2 to the gameBanana, it seems that i have been baned for some reason……

**Comment by soliddanii** [comment]
> errr,after i publish the v1.8.2 to the gameBanana, it seems that i have been baned for some reason……

Apparently the upload got automatically flagged, and a moderator has to manually aprove it. Hopefully it won't take long for the mod page to go back to normal. I'm pretty sure no rules were broken. Your actual account didn't get banned right?

> I plan on dropping the ability to have ZZZ be able to auto-refresh after application, it's been a waste of my time and I don't have a clue at this point, it just seems too in-depth for me.😭

I've been trying to get that working without success, for now. I'll let you know if I can do it in a reasonable amount of time.

> In the next version, I'm going to add the ability to add a cover to a mod by dragging and dropping an image, for which I have some learning to do.🧐

That's a feature I was really interested in having. Take a look at the [SkinSelectImpact](https://gamebanana.com/tools/12839) mod manager. The tool is quite ugly, but the _clipboard cut_ tool to set previews is great. Good luck with the feature!

**Comment by soliddanii** [comment]
> I plan on dropping the ability to have ZZZ be able to auto-refresh after application, it's been a waste of my time and I don't have a clue at this point, it just seems too in-depth for me

Ok. After several hours of research, and trying different libraries and methods for doing this I finally managed to get this feature working. It's fast and works withing js, no external executables. The bad news is the method requires launching the app with admin privileges or the game just ignores the input. The good news is I got it working without admin rights too, using an "trick", but we could just set a message near the feature checkbox warning the user that they have to configure the exe to start the app as admin if they want the feature to work. 

I'll clean the code and prepare a branch with a more detailed explanation in the coming days.

**Comment by XiaoLinXiaoZhu** [comment]
I mainly want to add the following features in the next release:
1. The mod info will also include URL information, which can let users know where the mod is coming from, keep an eye on whether the mod is updated, and make it easier to share
2. The modManager will be able to automatically try to read the ini file of the mod and analyze the shortcuts it contains. If it could, it would also be able to support the ability to customize mod's shortcuts.
3. Optimize the page layout: I've always felt that the left sidebar of the whole page is not very good-looking, especially the button layout in the bottom left corner, but I don't know how to modify it to make it more beautiful...... Originally, the number of buttons was relatively small, and it looked good in a row, but now it is very troublesome when there are more buttons...... For the time being, I'm going to change their layout to a staggered layout

**Pull request merged**
